### ISSUE TITLE
if backupSpec is not valid, link documentation

### ISSUE THREAD

**Issue by kaovilai** [migtools/oadp-non-admin#48]
The link would show up in status message of NAB/NAR error/warnings.

could be ENV that can be overridden in downstream CSV etc.

The link could be short link that can be dynamically updated in the future.

**Comment by mateusoliveira43** [comment]
which documentation would we link today :question: for example

**Comment by mateusoliveira43** [comment]
is not this a OADP (or Velero) enhancement :question: Can you give an example of a problem that would only happen in NAC, but not in OADP :question:

**Comment by mpryc** [comment]
It is kind of both.

1. The VeleroBackup within NonAdminBackup is incorrect (currently it's empty case only, but we will add namespace checking and possibly other checks). In this case only NAB object will know that something is wrong, because VeleroBackup will never be created in a first place. This is easy as we will have pre-check to find out if the VeleroBackup config aligns with NAB requirements.
2. The VeleroBackup got created as it was accepted by the NonAdminBackup, but the logs in VeleroBackup object indicates that something is wrong. We could consider adding another condition to a NonAdminBackup stating about configuration errors. This one is a bit more challenging, because not all errors in logs tells that config are not OK.

**Comment by mateusoliveira43** [comment]
I am still not sure if we should link any documentation

The issue request is to inform nonadmin user that even though NonAdminBackup spec is valid, resulting VeleroBackup spec is not valid, right?

In this case, I think we just need to check for `FailedValidation` phase in VeleroBackup object

> Reference https://github.com/openshift/velero/blob/9bff8b4d580e9d67832586856097f9474edb5bbb/pkg/apis/velero/v1/backup_types.go#L295-L297

and add `ValidationErrors` to NonAdminBackup status conditions

> Reference https://github.com/openshift/velero/blob/9bff8b4d580e9d67832586856097f9474edb5bbb/pkg/apis/velero/v1/backup_types.go#L370-L374

If `ValidationErrors` messages are not clear, I do not think linking any documentation would help here

Only thing to take care with this approach, is that NAB Status update design needs changes. If we hit this
- NonAdminBackup phase should go from created to another thing
- if reconciles return an error, should be terminal error
- if nonadmin user updates its spec, it should update already created VeleroBackup (or even delete VeleroBackup prior to when NonAdminBackup status updates).

Similar approach for NonAdminRestore

**Comment by mateusoliveira43** [comment]
After yesterday meeting, we decided that if users creates NonAdminBackup/NonAdminRestore that is valid for NAB/NAR controller, but fails Velero validation, user will have to delete NonAdminBackup/NonAdminRestore and recreate object to get out Velero `FailedValidation` state.

With this info, there is anything more we need to do related to this issue? Or it can be closed?

**Comment by kaovilai** [comment]
For failing velero validation, nothing to do. Can close for now.
