### ISSUE TITLE
Consider simplifying logic in reconcile loop for NAB. 

### ISSUE THREAD

**Issue by mpryc** [migtools/oadp-non-admin#62]
Alright, what about keeping as it is, but simplify `if`s :question: 
```go
	if reconcileExit || reconcileRequeue || reconcileErr != nil{
		return ctrl.Result{Requeue: reconcileRequeue, RequeueAfter: requeueTimeSeconds * time.Second}, reconcileErr
	}
```

_Originally posted by @mateusoliveira43 in https://github.com/migtools/oadp-non-admin/pull/54#discussion_r1591400725_

**Comment by mateusoliveira43** [comment]
Another places we need to change after today's discussion
- If only NAB Status is updated, predicate should not return true, which would re trigger Reconcile
- Only perform one update call per object (in this case, it is only NAB) per Reconcile, to avoid race conditions (the update call can update multiple things). This is being fixed in https://github.com/migtools/oadp-non-admin/pull/73
- Remove NAB Spec change by Reconcile for now and evaluate later if we want that. This is being tracked here https://github.com/migtools/oadp-non-admin/issues/77
